### ISSUE TITLE
(Shadow): Shadow support for client devices

### ISSUE THREAD

**Issue by smartnimbus** [aws-greengrass/aws-greengrass-shadow-manager#101]
HI All
I have the Greengrass v2 working with freertos following these steps https://docs.aws.amazon.com/greengrass/v2/developerguide/client-devices-tutorial.html
However, has anyone manage to use the Local Shadow with client devices?
https://docs.aws.amazon.com/greengrass/v2/developerguide/interact-with-shadows.html

I did raise this on Freertos forum https://github.com/aws/amazon-freertos/issues/3419
and was advised to use local pub/sub with aws-greengrass-mqtt-bridge, however I can get $aws/things/MyThingName/shadow/name/myNamedShadow/update/accepted to work and nothing else. 

I have tried every combination of accessControl and mqttTopicMapping and only /update/accepted works. 
can someone point me in the right direction?

	"mqttTopicMapping": {
		"ClientDevice1Mapping": {
			"topic": "$aws/things/NOD0R-01/shadow/name/+/+",
			"source": "LocalMqtt",
			"target": "Pubsub"
		},
		"ClientDevice2Mapping": {
			"topic": "$aws/things/NOD0R-01/shadow/name/+/+/+",
			"source": "Pubsub",
			"target": "LocalMqtt"
		}
	}

	"accessControl": {
		"aws.greengrass.ShadowManager": {
			"policyId1": {
				"policyDescription": "Allows access to shadows",
				"operations": [
					"aws.greengrass#GetThingShadow",
					"aws.greengrass#UpdateThingShadow",
					"aws.greengrass#DeleteThingShadow"
				],
				"resources": [
					"$aws/things/NOD0R-01/shadow",
					"$aws/things/NOD0R-01/shadow/name/test"
				]
			}
		}
	}

**Comment by nikkhilmuthye** [comment]
Hi,

Currently shadow support is only available for components running inside the GG Core which can talk over IPC. We have specific Shadow IPC operations that components can invoke for shadow state management.

We are actively working on adding shadow support for client devices. The release timeline is not finalized yet.

~Nikkhil

**Comment by smartnimbus** [comment]
Thank you Nikkhil
do you have a good Python example for component to interact with shadow-manager?

**Comment by nikkhilmuthye** [comment]
You can find examples for interacting with shadow manager using IPC [here](https://docs.aws.amazon.com/greengrass/v2/developerguide/ipc-local-shadows.html). This documentation provides examples in Java and Python using the GG v2 SDK.

**Comment by rodmaz** [comment]
We are currently running into some issues regarding this. However according to [latest documentation](https://docs.aws.amazon.com/greengrass/v2/developerguide/work-with-client-device-shadows.html#enable-shadow-manager-client-devices), this is fully supported when used with MQTT Bridge component.
Why is this ticket still open then?

**Comment by MikeDombo** [comment]
Yes that's a good point, this isn't needed. Bridge works with shadows as intended.
