### ISSUE TITLE
(configuration): ShadowManager stops responding to configuration updates

### ISSUE THREAD

**Issue by jbutler** [aws-greengrass/aws-greengrass-shadow-manager#129]
**Describe the bug**
Shadow Manager can reach a state where it effectively stops listening to configuration updates. While in this state, it is not possible for customers to update ShadowManager configuration to add / remove shadows, or to change sync behavior. This leads to customer frustration since their configuration may actually be correct, but ShadowManager does not respect it. Restarting Greengrass resolves the issue.

This issue is caused by the fact that ShadowManager subscribes to individual configuration nodes during initialization (e.g. [here](https://github.com/aws-greengrass/aws-greengrass-shadow-manager/blob/5a16d1723377a41aee6d270cffc3dbd929ef49f4/src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java#L245), and [here](https://github.com/aws-greengrass/aws-greengrass-shadow-manager/blob/5a16d1723377a41aee6d270cffc3dbd929ef49f4/src/main/java/com/aws/greengrass/shadowmanager/ShadowManager.java#L281)). These configuration node subscriptions are "lost" if the node gets deleted. This occurs if a deployment which performs a `RESET` on the configuration node occurs.

**To Reproduce**
1. Deploy ShadowManager component
2. Perform a second deployment which performs a ShadowManager configuration reset (`RESET: [""]`)
3. Perform a third deployment which configures SM to sync a shadow

**Expected behavior**
ShadowManager should respond to the 3rd deployment by beginning to sync the specified shadow.

**Actual behavior**
It does not sync the new shadow until Greengrass is restarted.

**Environment**
 - OS: [e.g. Ubuntu 20.04]
 - JDK version:
 - Nucleus version:
 - Shadow Manager version:

**Additional context**

E.g. what is the impact of the bug?

**Comment by saranyailla** [comment]
Closed as part of [shadow manager 2.2.4 release]( https://github.com/aws-greengrass/aws-greengrass-shadow-manager/releases/tag/v2.2.4).
